spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/payment_service?currentSchema=batch
    username:
    password:
    driver-class-name: org.postgresql.Driver

  batch:
    jdbc:
      initialize-schema: never   # crea tablas internas si no existen
      schema: classpath:org/springframework/batch/core/schema-postgresql.sql
    job:
      enabled: true
      name: paymentJob

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: batch

  logging:
    level:
      org.springframework.batch: DEBUG

